package io.roadbook.karoo.data

import android.content.Context
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import timber.log.Timber

/**
 * A downloadable POI region shown in the picker. Mirrors an entry of the bundled
 * `assets/regions.json`, generated by the data pipeline from `tools/poi-db/regions.ts`
 * (`npm run gen:regions-json`), so the two never drift.
 *
 * This carries only what the picker needs offline (label + group). Download details —
 * file, size, sha256 — come from the live manifest ([RegionManifest]) fetched on demand
 * for the region the rider selects.
 */
@Serializable
data class Region(
    val id: String,
    val label: String,
    /** Picker section: "Germany" (Complete + Bundesländer) or "Europe" (countries). */
    val group: String,
) {
    companion object {
        /** The region the bundled first-run seed installs as. */
        const val SEED_REGION_ID = "germany"

        /**
         * Whether [installed] (the set of directly-installed region ids) covers [rowId].
         * A region covers itself; installing "germany" (Complete) additionally covers every
         * `germany-<bundesland>` row, since that download contains them all. Used by the
         * picker to show ✓ on Bundesländer once Germany is installed.
         */
        fun covers(installed: Set<String>, rowId: String): Boolean =
            rowId in installed ||
                (SEED_REGION_ID in installed && rowId.startsWith("$SEED_REGION_ID-"))
    }
}

/**
 * The live region manifest (a GitHub release asset). Lists every downloadable region
 * with its file + integrity metadata. [schemaVersion] must equal the app's
 * [PoiDatabase.BUNDLED_DB_VERSION]; a mismatch means the app is too old/new for these
 * files and the download must be refused.
 */
@Serializable
data class RegionManifest(
    val schemaVersion: Int,
    /** Absolute URL prefix; a region file lives at `baseUrl + entry.file`. */
    val baseUrl: String,
    val regions: List<RegionManifestEntry>,
)

@Serializable
data class RegionManifestEntry(
    val id: String,
    val label: String,
    val group: String,
    /** Filename under [RegionManifest.baseUrl], e.g. `germany-hessen-v5.sqlite.gz`. */
    val file: String,
    val bytesGz: Long,
    val bytesRaw: Long,
    val poiCount: Int,
    /** Lowercase hex SHA-256 of the gzipped file, verified after download. */
    val sha256: String,
)

/** Reads the bundled region catalog so the picker renders without a network call. */
object RegionCatalog {
    private const val ASSET = "regions.json"
    private val json = Json { ignoreUnknownKeys = true }

    /** Parse `assets/regions.json`; empty list if the asset is missing/unreadable. */
    fun load(context: Context): List<Region> =
        runCatching {
            context.applicationContext.assets.open(ASSET).use { input ->
                json.decodeFromString<List<Region>>(input.readBytes().decodeToString())
            }
        }.onFailure { Timber.e(it, "failed to read $ASSET") }.getOrDefault(emptyList())
}
